/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 porsche.gltf -T 
Files: porsche.gltf [106.38KB] > porsche-transformed.glb [3.94MB] (-3599%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/porsche-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_32.geometry} material={materials.coat} scale={0.812} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.paint} scale={0.812} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['930_chromes']} scale={0.812} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.black} scale={0.812} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['930_lights']} position={[0, 0.725, 3.256]} scale={0.812} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.glass} scale={0.812} />
      <mesh geometry={nodes.Object_136.geometry} material={materials['930_stickers']} scale={0.812} />
      <mesh geometry={nodes.Object_105.geometry} material={materials['930_plastics']} scale={0.812} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['930_lights_refraction']} scale={0.812} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['930_rim']} position={[-0.826, 0.453, 1.603]} rotation={[0.503, -0.286, 0.154]} scale={0.812} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['930_tire']} position={[-0.826, 0.453, 1.603]} rotation={[0.503, -0.286, 0.154]} scale={0.812} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.plate} position={[0, 0.555, -2.13]} scale={[0.812, 0.78, 0.812]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials['930_wunderbaum']} position={[-0.002, 1.285, 0.542]} scale={0.812} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.material_0} position={[0, 0.118, 0.225]} scale={[1.558, 1.558, 3.117]} />
    </group>
  )
}

useGLTF.preload('/porsche-transformed.glb')
